baseURL = "https://laur1s.github.io/"
languageCode = "en-us"
title = "AWS For Humans"
theme = "ananke"
Paginate = 5
disqusShortname = "laur1s"
[params]
  twitter = "https://twitter.com/LaurynasT2"
  title = "AWS For Humans"
  author = "Laurynas Tumosa"
  description = "Blog about AWS and DevOps"
  background_color_class = "bg-black"
  featured_image = "/images/aws.webp"
  profilePicture = "/images/profile.jpg"
  summarylength = 4000
  show_reading_time = true
  favicon = "/images/favicon.ico"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

[params.simpleAnalytics]
enable = true

