baseURL = "http://example.org/"
languageCode = "en-us"
title = "DevOps For Humans"
theme = "anatole"
[params]
  title = "DevOps For Humans"
  author = "Laurynas Tumosa"
  description = "Notes about Devops, Cloud, AWS, Terraform and other things from my work as a Devops engineer"
  profilePicture = "images/profile.jpg"

