baseURL = "https://laur1s.github.io/"
languageCode = "en-us"
title = "DevOps For Humans"
theme = "anatole"
[params]
  title = "DevOps For Humans"
  author = "Laurynas Tumosa"
  description = "Notes about Devops, Cloud, AWS, Terraform and other things from my work as a Devops engineer."
  profilePicture = "images/profile.jpg"
  summarylength = 4000

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

[params.simpleAnalytics]
enable = true
